In [4]:
from differential_evolution import optimize
from timer import Timer

In [5]:
def matrix_cost(M):
    x = torch.det(torch.bmm(M,M) + M + 1)
    return x*x

In [6]:
optimize(matrix_cost, pop_size = 60, dim=(5,5), epochs=Timer(10))

(1.4518942634822452e-06,
 tensor([[-0.1213,  0.7456, -0.2790, -0.4660,  1.8336],
         [-0.4204, -1.1127,  2.3394, -1.4035, -3.0741],
         [ 2.4468,  0.0767,  0.2665, -0.2187,  1.8682],
         [ 0.8435, -1.1646,  2.0191, -1.1436, -1.4431],
         [ 1.0106, -1.2558,  0.7051,  0.4762, -0.7508]]))

In [7]:
optimize(matrix_cost, pop_size = 60, dim=(5,5), epochs=100)

(1.5474828614969738e-05,
 tensor([[-4.2676e-01,  8.4523e-01, -2.4238e+00, -6.9477e-01,  3.4377e-01],
         [-8.8519e-01, -1.0288e+00, -1.3508e+00, -6.3709e-01, -1.0409e+00],
         [ 1.2098e+00,  6.4819e-01,  7.0985e-01,  6.4997e-01,  1.7830e+00],
         [-7.0817e-01, -2.7000e-01, -1.4124e-01, -3.4432e-01, -3.6290e-01],
         [-2.0654e-01,  1.6984e-03, -1.1640e+00, -1.4207e+00, -1.5112e+00]]))

In [8]:
optimize(matrix_cost, pop_size = 60, dim=(5,5), epochs=range(100))

(0.05211026594042778,
 tensor([[-1.7749, -1.6270, -0.6224, -1.0075, -1.0314],
         [ 1.1337,  0.7654,  0.7486, -0.2459, -1.0981],
         [ 0.1570,  1.8292, -0.7918,  0.3977,  1.0390],
         [-1.0919,  0.7628, -2.8400,  0.8305,  0.0417],
         [-0.3541,  0.2810,  1.1724, -0.7322,  1.0674]]))

In [9]:
optimize(matrix_cost, pop_size = 60, dim=(5,5), epochs=list(range(1009)))

(1.057436094242803e-07,
 tensor([[ 0.7152, -0.0198, -0.4961,  1.2521,  0.7508],
         [ 2.1019,  2.1711, -2.2907, -2.7898,  1.5381],
         [ 1.4705,  0.6886, -1.2266, -0.6548,  0.9765],
         [ 2.0926,  1.9785,  0.8231,  0.7062,  0.8181],
         [ 1.1983, -0.4962,  0.4377,  1.0981, -0.3262]]))